title: Mark Berthelemy
name: Mark Berthelemy

description: 'Where knowledge meets technology'
sub-description: 'Connecting the dots to business success'

url: https://mark.berthelemy.net

collections_dir: collections

collections:

include: ['_pages']

plugins:
  - jekyll-sitemap
  - jekyll-feed
title: Mark Berthelemy
description: Advice and support at the intersection of knowledge, technology and business
author: Mark Berthelemy

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      sitemap: false
