title: Mark Berthelemy
name: Mark Berthelemy

description: 'Independent learning and knowledge systems consultant'
simple_description: 'Information architect'
long-description: 'Experienced and independent consultant able to help with supplier selection, system implementation projects, information architecture and learning design leadership.'
sub-description: 'Connecting the dots to business success'

url: https://mark.berthelemy.net
domain: mark.berthelemy.net

collections_dir: collections

collections:
  lessons:
    output: true
    permalink: /:collection/:path
  resources:
    output: true
    permalink: /:collection/:path

levels-order:
 - Novice
 - Intermediate
 - Advanced

include: ['_pages']

plugins:
  - jekyll-sitemap
  - jekyll-feed

author: Mark Berthelemy

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      sitemap: false
    scope:
      path: ""
      type: "lessons"
    values:
      layout: lesson
      style: style1
    scope:
      path: ""
      type: "toolkit"
    values:
      layout: tool
