title: Mark Berthelemy
name: Mark Berthelemy

description: 'Independent technology and digital learning solutions architect / consultant / implementation manager and IT generalist'

url: https://mark.berthelemy.net

collections_dir: collections

collections:

include: ['_pages']
