title: Mark Berthelemy
name: Mark Berthelemy

description: 'Digital Problem Solver'
sub-description: 'Independent technology and digital learning solutions architect / consultant / implementation manager and IT generalist'

url: https://mark.berthelemy.net

collections_dir: collections

collections:

include: ['_pages']

plugins:
  - jekyll-sitemap

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      sitemap: false
