title: Mark Berthelemy
name: Mark Berthelemy

description: 'Independent Digital Problem Solver'
sub-description: 'consultant solutions architect, project manager and IT generalist'

url: https://mark.berthelemy.net

collections_dir: collections

collections:

include: ['_pages']

plugins:
  - jekyll-sitemap
  - jekyll-feed
title: Mark Berthelemy
description: Advice and opinion about learning, technology and business
author: Mark Berthelemy

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      sitemap: false
