title: Mark Berthelemy
name: Mark Berthelemy

description: 'Consultant solutions architect'
simple_description: 'Consultant solutions architect'
long-description: 'Experienced and independent consultant able to help in situations requiring translation between technical and non-technical people.'
sub-description: 'Connecting the dots to business success'

url: https://mark.berthelemy.net
domain: mark.berthelemy.net

collections_dir: collections

collections:
  lessons:
    output: true
    permalink: /:collection/:path
  toolkit:
    output: true
    permalink: /:collection/:path
  expertises:
    output: true
    sort_by: order
    permalink: /:collection/:path

levels-order:
 - Novice
 - Intermediate
 - Advanced

include: ['_pages']

plugins:
  - jekyll-sitemap
  - jekyll-feed

author: Mark Berthelemy

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      sitemap: false
    scope:
      path: ""
      type: "drafts"
    values:
      sitemap: false
    scope:
      path: ""
      type: "lessons"
    values:
      layout: lesson
      style: style1
      sitemap: false
    scope:
      path: ""
      type: "toolkit"
    values:
      layout: tool
      sitemap: false
    scope:
      path: ""
      type: "expertises"
    values:
      layout: expertise
    scope:
      path: "/projects/*"
    values:
      sitemap: false
    scope:
      path: "/google*"
    values:
      sitemap: false
