title: Mark Berthelemy
name: Mark Berthelemy

description: 'Experienced IT and training professional, able to take on large and small projects'

url: https://mark.berthelemy.net

collections_dir: collections

collections:

include: ['_pages']
