title: Mark Berthelemy Consulting
name: Mark Berthelemy Consulting

description: 'Learning Technology Consultant'
simple_description: 'Learning Technology Consultant'
long-description: 'I help organisations to scale their learning solutions, with cost-effective platforms, integrated processes and clear communication.'
sub-description: 'Connecting the dots to business success'

url: https://consulting.berthelemy.net
domain: consulting.berthelemy.net

collections_dir: collections

collections:
  tag:
    output: true
    permalink: /:collection/:path
  lessons:
    output: true
    permalink: /:collection/:path
  toolkit:
    output: true
    permalink: /:collection/:path
  resources:
    output: true
    permalink: /:collection/:path
  expertise:
    output: true
    sort_by: order
    permalink: /:collection/:path

levels-order:
 - Novice
 - Intermediate
 - Advanced

include: ['_pages']

plugins:
  - jekyll-sitemap
  - jekyll-feed

author: Mark Berthelemy

defaults:
  - scope:
      path: ""
      type: tag
    values:
      layout: "tag"
      sitemap: true
  - scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      sitemap: true
  - scope:
      path: ""
      type: "drafts"
    values:
      sitemap: false
  - scope:
      type: "lessons"
    values:
      layout: lesson
      style: style1
      sitemap: false
  - scope:
      type: "toolkit"
    values:
      layout: tool
      sitemap: false
  - scope:
      path: ""
      type: "expertise"
    values:
      layout: expertise
  - scope:
      path: "/google*"
    values:
      sitemap: false
