- title: Strategic consulting
  icon: fa-arrow-circle-right
  text:
    - Learning technology review
    - Business case preparation
    - User experience reviews
    - Solutions architecture design

- title: Projects (agile & waterfall)
  icon: fa-project-diagram
  text:
    - Workshop facilitation
    - Lessons learned exercises
    - Project manager coaching
    - Troubleshooting and training

- title: Moodle
  icon: fa-graduation-cap
  text:
    - Design and setup
    - System administration
    - Administrator & tutor coaching
    - Troubleshooting and training

- title: Procurement support
  icon: fa-shopping-basket
  text:
    - Needs analysis
    - Long and short-listing
    - Documentation
    - Supplier selection
